### ISSUE TITLE
Problems in opening project in Unity

### ISSUE THREAD

**Issue by Matrixchung** [federicodangelo/CubeWorld#3]
Hi there,these days i'm trying to get started with Unity through your good example as i'm a completely c++ programmer before.But when i open the CubeWorld project in correct version of Unity,it only opens an empty scene with all assets in correct folder.And when i try to build the project,the output exe acts the same.
I found a Main.unity included but i failed to open it.I think there must be some additional settings required but i cant find out what goes wrong.
Thanks again for your help!

**Comment by flecoq** [comment]
Hi there,
I have the same problem...
Matrixchung, have you solved it ?
Thank you for your help !

**Comment by federicodangelo** [comment]
I have updated the project to work in unity 2019.3.13f1 , tell me if that's enough for you!

**Comment by flecoq** [comment]
Hi Frederico
,
Thank u so much for your help.
I ve installed it on unity 2019.3.12f1. Unfortunalty, when i click on "play" button, my processor is running strongly but the scene is always empty :( 

I ve found 1 console error:
Object GameObject (named 'FxExplosion') has multiple entries of the same Object component. Removing it!

Maybe i have to include or link CubeWorldLibrary with CubeWorld projet, or something like that ? Can i find logs somewhere too ?

Best regards

**Comment by federicodangelo** [comment]
Are you targeting an stand alone build? Windows / Mac / Linux?

**Comment by federicodangelo** [comment]
![image](https://user-images.githubusercontent.com/1854523/81477298-6cfcb980-91ed-11ea-832f-cf78e7ee7352.png)

**Comment by flecoq** [comment]
The game works now :) 
I ve not found the Main scene in the Assets root, because the Projet tree displays only the folders...
Thks u so much
